name: My First Workflow

on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@4

        - name: Welcome messages
          run: echo "My frist Github Actions job"
        
        - name: List files
          run: ls
        
        - name: Read file
          run: cat README.md
    