name: Exploring Variables and Secrets

on: push

###################################################################
##################   Workflow level variables  ####################
###################################################################
##These variables are accessible to all the jobs in the workflow ##
###################################################################

env:
    {{ vars.CONTAINER_REGISTRY}}: docker.io
    IMAGE_NAME: github-actions-nginx

jobs: 
    docker:
        runs-on: ubuntu-latest
        steps:
        - name: Docker Build
          run: echo docker build -t ${{ vars.CONTAINER_REGISTRY}}/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest
        
        - name: Docker Login
          run: echo docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
        
        - name: Docker Publish
          run: echo docker push ${{ vars.CONTAINER_REGISTRY}}/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest
    

    deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps:
        - name: Docker Run
          run: echo docker run -d -p 8080:80 docker.io/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

# ###################################################################
# ##################   Job level comments     #######################
# ###################################################################

# jobs: 
#     docker:
#         env:
#             {{ vars.CONTAINER_REGISTRY}}: docker.io
#             DOCKER_USERNAME: moritlha
#             IMAGE_NAME: github-actions-nginx
#         runs-on: ubuntu-latest
#         steps:
#         - name: Docker Build
#           run: docker build -t ${{ vars.CONTAINER_REGISTRY}}/{{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest
        
#         - name: Docker Login
#           env:
#             DOCKER_PASSWORD: s3curePaSsw0rd
#           run: docker login --username={{ vars.DOCKER_USERNAME }} --password=$DOCKER_PASSWORD
        
#         - name: Docker Publish
#           run: echo docker push ${{ vars.CONTAINER_REGISTRY}}/{{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest
    

#     deploy:
#         env:
#             {{ vars.CONTAINER_REGISTRY}}: docker.io
#             DOCKER_USERNAME: moritlha
#             IMAGE_NAME: github-actions-nginx
#         needs: docker
#         runs-on: ubuntu-latest
#         steps:
#         - name: Docker Run
#           run: docker run -d -p 8080:80 docker.io/{{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest



###################################################################
##################   Step level comments     #######################
###################################################################
# jobs: 
#     docker:
#         runs-on: ubuntu-latest
#         steps:
#         - name: Docker Build
#           env:
#             {{ vars.CONTAINER_REGISTRY}}: docker.io
#             DOCKER_USERNAME: moritlha
#             IMAGE_NAME: github-actions-nginx
#           run: docker build -t ${{ vars.CONTAINER_REGISTRY}}/{{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest
        
#         - name: Docker Login
#           env:
#             DOCKER_PASSWORD: s3cUrePassw0rd
#             DOCKER_USERNAME: moritlha
#             IMAGE_NAME: github-actions-nginx
#           run: docker login --username={{ vars.DOCKER_USERNAME }} --password=$DOCKER_PASSWORD
        
#         - name: Docker Publish
#           env:
#             {{ vars.CONTAINER_REGISTRY}}: docker.io
#             DOCKER_USERNAME: moritlha
#             IMAGE_NAME: github-actions-nginx
#           run: echo docker push ${{ vars.CONTAINER_REGISTRY}}/{{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest
    

#     deploy:
#         needs: docker
#         runs-on: ubuntu-latest
#         steps:
#         - name: Docker Run
#           env:
#             {{ vars.CONTAINER_REGISTRY}}: docker.io
#             DOCKER_USERNAME: moritlha
#             IMAGE_NAME: github-actions-nginx
#           run: docker run -d -p 8080:80 docker.io/{{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest